// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASaz2Eyj7GPyeShFIBpW9lcVRYbnA8-OU',
    appId: '1:721232285881:web:37cc9a4413761669b98b68',
    messagingSenderId: '721232285881',
    projectId: 'testing-13945',
    authDomain: 'testing-13945.firebaseapp.com',
    storageBucket: 'testing-13945.firebasestorage.app',
    measurementId: 'G-9LVQ0ZBWLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1olaE4LZIhuo6PjbFyXa2hl45s7wVPU',
    appId: '1:721232285881:android:f289c78fd3df48ffb98b68',
    messagingSenderId: '721232285881',
    projectId: 'testing-13945',
    storageBucket: 'testing-13945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyzyFf1IZndBeTsr7ZBPG8_hcf7gIW4TE',
    appId: '1:721232285881:ios:421d4bfaf06e3813b98b68',
    messagingSenderId: '721232285881',
    projectId: 'testing-13945',
    storageBucket: 'testing-13945.firebasestorage.app',
    iosBundleId: 'com.example.streamAppFullStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyzyFf1IZndBeTsr7ZBPG8_hcf7gIW4TE',
    appId: '1:721232285881:ios:421d4bfaf06e3813b98b68',
    messagingSenderId: '721232285881',
    projectId: 'testing-13945',
    storageBucket: 'testing-13945.firebasestorage.app',
    iosBundleId: 'com.example.streamAppFullStack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASaz2Eyj7GPyeShFIBpW9lcVRYbnA8-OU',
    appId: '1:721232285881:web:e68ff69140d5a8d4b98b68',
    messagingSenderId: '721232285881',
    projectId: 'testing-13945',
    authDomain: 'testing-13945.firebaseapp.com',
    storageBucket: 'testing-13945.firebasestorage.app',
    measurementId: 'G-9JXV56B0LC',
  );

}